mo_hospitals = [
    "Advanced Healthcare Med Center",
    "Hannibal Regional Hospital",
    "NW Missouri Psych Rehab Center",
    "SSM DePaul Health Center",
    "Western MO Mental Health Cntr",
    "Audrain Medical Center",
    "Harrison County Comm Hospital",
    "Ozarks Medical Center",
    "SSM Rehab",
    "Wright Memorial Hospital",
    "Barnes-Jewish Hospital",
    "Hawthorn Child Psych Hospital",
    "Parkland Health Center",
    "SSM St Joseph Health Center",
    "Barnes-Jewish St Peters Hosp",
    "Heartland Behavioral Hlth Serv",
    "Parkland Hlth Center-Bonne Terre",
    "SSM St Joseph Hospitalof Kirkwood",
    "Barnes-Jewish West County Hosp",
    "Heartland Regional Medical Center",
    "Pemiscot Memorial Hlth System",
    "SSM St Joseph Hospital West",
    "Barton Cnty Memorial Hospital",
    "Hedrick Medical Center",
    "Perry County Memorial Hospital",
    "SSM St Mary's Health Center",
    "Bates County Memorial Hospital",
    "Hermann Area District Hospital",
    "Phelps Cnty Regional Med Cntr",
    "St Alexius Hospital",
    "Boone Hospital Center",
    "Howard A Rusk Rehab Center",
    "Pike County Memorial Hospital",
    "St Anthony's Medical Center",
    "Bothwell Regional Health Center",
    "I-70 Medical Center",
    "Poplar Bluff Regional Med Center",
    "St Francis Hospital & Hlth Servs",
    "Callaway Community Hospital",
    "Jefferson Memorial Hospital",
    "Putnam County Memorial Hospital",
    "St John's Hospital",
    "Cameron Regional Medical Center",
    "John J Pershing VA Med Center",
    "Ranken Jordan",
    "St John's Hospital in Aurora",
    "Capital Region Medical Center",
    "Kindred Hospital-Kansas City",
    "Ray County Memorial Hospital",
    "St John's Hospital in Cassville",
    "Carroll County Memorial Hospital",
    "Kindred Hospital in St Louis",
    "Rehab Institute of St Louis",
    "St John's Hospital in Lebanon",
    "Cass Medical Center",
    "Lafayette Regional Health Center",
    "Research Belton Hospital",
    "St John's Mercy Hospital",
    "Cedar County Memorial Hospital",
    "Lake Regional Health System	Research Medical Center",
    "St John's Mercy Medical Center",
    "Centerpoint Medical Center",
    "Lakeland Regional Hospital",
    "Research Medical Center on East Meyer Blvd",
    "St John's Regional Medical Center",
    "CenterPointe Hospital",
    "Landmark Hospital",
    "Research Psychiatric Center",
    "St John's St Francis Hospital",
    "Children's Mercy Hospital & Clinic",
    "Lee's Summit Medical Center",
    "Ripley County Mem Hospital",
    "St Joseph Medical Center",
    "Christian Hospital",
    "Lester E Cox Medical Centers",
    "Royal Oaks Hospital",
    "St Louis Children's Hospital",
    "Citizens Memorial Hospital",
    "Liberty Hospital",
    "Sac-Osage Hospital",
    "St Louis Psych Rehab Center",
    "Columbia Regional Hospital",
    "Lincoln County Medical Center",
    "Saint Francis Medical Center",
    "St Luke's Hospital",
    "Community Hospital Association",
    "Madison Medical Center",
    "Saint Louis University Hospital",
    "St Mary's Medical Center",
    "Cooper County Mem Hospital",
    "McCune-Brooks Hospital",
    "Saint Luke's Cancer Institute",
    "St Marys Health Center",
    "Cox Monett Hospital	Medical Center for Federal Prisoners",
    "Saint Luke's East-Lee's Summit",
    "St Genevieve County Memorial Hospital",
    "Crittenton Children's Center",
    "Metro St Louis Psych Center",
    "Saint Luke's Hospital",
    "Sullivan County Memorial Hospital",
    "Des Peres Hospital",
    "Mid-Missouri Mental Health Center",
    "Saint Luke's Northland Hospital",
    "SW Missouri Psych Rehab Center",
    "Doctors Hospitalof Springfield",
    "Mineral Area Regional Med Center",
    "Saint Luke's Northland Hospital",
    "Texas County Memorial Hospital",
    "DuBuis Hospital of St Louis	Missouri",
    "Baptist Hospital in Sullivan",
    "Salem Mem District Hospital",
    "Truman Medical Center @Hsp Hill",
    "Ellett Memorial Hospital",
    "Missouri Baptist Medical Center",
    "Samaritan Memorial Hospital",
    "Truman Medical Center-Lakewood",
    "Excelsior Springs Medical Center",
    "Missouri Delta Medical Center",
    "Scotland County Mem Hospital",
    "Truman Memorial Veterans Hosp",
    "Fitzgibbon Hospital	Missouri Rehabilitation Center",
    "Select Specialty Hospital",
    "Twin Rivers Reg Med Center",
    "Freeman Health System",
    "Missouri Southern Healthcare",
    "Select Specialty Hospital",
    "Two Rivers Psych Hospital",
    "Freeman Neosho Hospital",
    "Moberly Regional Medical Center",
    "Shriners Hosps for Children",
    "University of MO Hospital & Clinic",
    "University of Missouri Hospital & Clinic",
    "Fulton State Hospital",
    "Nevada Regional Medical Center",
    "Skaggs Community Health Center",
    "Veterans Affairs Med Center",
    "Gen John J Pershing Mem Hospital North Kansas City Hospital",
    "Southeast Missouri Hospital",
    "Veterans Affairs Medical Center",
    "Gen Leonard Wood Army Hospital",
    "Northeast Regional Medical Center",
    "Southeast MO Mental Hlth Center",
    "Washington County Mem Hospital",
    "Golden Valley Memorial Hospital",
    "Northwest Medical Center",
    "SSM Cardinal Glennon Child Center",
    "Western Missouri Medical Center",
]
