MO_SCHOOLS = [
    "Adair County R-I High School",
    "Adair County R-II High School",
    "Kirksville High School",
    "Life Church School",
    "North Andrew County High School",
    "Savannah High School",
    "Fairfax High School",
    "Rock Port High School",
    "Tarkio High School",
    "Community High School",
    "Van-Far High School",
    "Mexico Senior High School",
    "Missouri Military Academy",
    "Cassville High School",
    "Exeter High School",
    "Monett High School",
    "Purdy High School",
    "Southwest High School",
    "Wheaton High School",
    "Golden City High School",
    "Lamar High School",
    "Liberal High School",
    "Adrian High School",
    "Hume High School",
    "Miami High School",
    "Rich Hill High School",
    "Ballard High School",
    "Butler High School",
    "Cole Camp High School",
    "Lincoln High School",
    "Warsaw High School",
    "Leopold High School",
    "Meadow Heights High School",
    "Woodland High School",
    "Zalma High School",
    "Hallsville High School",
    "Harrisburg High School",
    "Southern Boone High School",
    "Sturgeon High School",
    "Centralia High School",
    "Sunnydale Adventist Academy",
    "David H. Hickman High School",
    "Frederick Douglass High School",
    "Muriel Battle High School",
    "Rock Bridge High School",
    "Christian Fellowship School",
    "Columbia Independent School",
    "Heritage Academy",
    "Tolton High School",
    "University of Missouri High School",
    "DeKalb High School",
    "East Buchanan County High School",
    "Mid-Buchanan County High School",
    "Benton High School",
    "St. Joseph Central High School",
    "Lafayette High School",
    "Baptist Temple Schools",
    "Bishop Le Blond High School",
    "St. Joseph Christian School",
    "South Park Christian Academy",
    "Neelyville High School",
    "Twin Rivers High School",
    "Agape Christian School",
    "Poplar Bluff High School",
    "Southern Missouri Christian School",
    "Westwood Baptist Academy",
    "Zion Lutheran School",
    "Braymer High School",
    "Breckenridge High School",
    "Penney High School",
    "Polo High School",
    "Fulton High School",
    "New Bloomfield High School",
    "North Callaway High School",
    "South Callaway High School",
    "Climax Springs High School",
    "Macks Creek High School",
    "Stoutland High School",
    "Camden Christian School",
    "Camdenton High School",
    "Delta High School",
    "Oak Ridge High School",
    "Cape Central High School",
    "Cape Girardeau Career & Technology Center",
    "Eagle Ridge Christian School",
    "Notre Dame Regional High School",
    "Jackson High School",
    "Saxony Lutheran High School",
    "Bosworth High School",
    "Carrollton High School",
    "Hale High School",
    "Norborne High School",
    "Tina-Avalon High School",
    "East Carter County High School",
    "Van Buren High School",
    "Archie High School",
    "Drexel High School",
    "Harrisonville High School",
    "Midway High School",
    "Raymore-Peculiar High School/Freshman Center",
    "Sherwood High School",
    "Training Center Christian School",
    "Belton High School/Freshman Center",
    "Heartland High School",
    "Hope Baptist Christian School",
    "Pleasant Hill High School",
    "El Dorado Springs",
    "El Dorado Christian School",
    "El Dorado Springs High School",
    "Agape Baptist Academy",
    "Stockton High School",
    "Brunswick High School",
    "Keytesville High School",
    "Northwestern High School",
    "Salisbury High School",
    "Billings High School",
    "Chadwick High School",
    "Clever High School",
    "Nixa Public High School",
    "Ozark High School",
    "Sparta High School",
    "Faith Christian School",
    "Spokane High School",
    "Clark County High School",
    "Excelsior Springs High School",
    "Kearney High School",
    "Outreach Christian Education School",
    "Smithville High School",
    "Liberty High School",
    "Liberty North High School",
    "Eagle Heights Christian School",
    "Faith Academy",
    "North Kansas City High School",
    "Northland Christian School",
    "Oak Park High School",
    "Staley High School",
    "Winnetonka High School",
    "St. Pius X High School",
    "Cameron High School",
    "Lathrop High School",
    "Plattsburg High School",
    "Russellville High School",
    "Eugene High School",
    "Blair Oaks High School",
    "Calvary Lutheran High School",
    "Central Baptist Christian Academy",
    "Helias Catholic High School",
    "Jefferson City High School/Simonsen 9th Grade Center",
    "Lighthouse Preparatory Academy",
    "Boonville High School",
    "Bunceton High School",
    "Otterville High School",
    "Pilot Grove High School",
    "Prairie Home High School",
    "Bourbon High School",
    "Cuba High School",
    "Meramec Valley Christian School",
    "Steelville High School",
    "Dadeville High School",
    "Everton High School",
    "Greenfield High School",
    "Lockwood High School",
    "Buffalo High School",
    "Gallatin High School",
    "North Daviess High School",
    "Pattonsburg High School",
    "Tri-County High School",
    "Winston High School",
    "Maysville High School",
    "Osborn High School",
    "Stewartsville High School",
    "Union Star High School",
    "Salem High School",
    "Ava High School",
    "Mt. Zion Bible Academy",
    "Campbell High School",
    "Clarkton High School",
    "Holcomb High School",
    "Malden High School",
    "Senath-Hornersville High School",
    "Southland High School",
    "Kennett Christian Academy",
    "Kennett High School",
    "Crosspoint Christian School",
    "The Fulton School at St. Albans",
    "Pacific High School",
    "New Haven High School",
    "Sullivan High School",
    "Union High School",
    "Cornerstone Baptist Academy",
    "St. Clair High School",
    "Four Rivers Career Center",
    "St. Francis Borgia Regional High School",
    "Washington High School",
    "Hermann High School",
    "Owensville High School",
    "Albany High School",
    "King City High School",
    "Stanberry High School",
    "Ash Grove High School",
    "Fair Grove High School",
    "Logan-Rogersville High School",
    "Republic High School",
    "Strafford High School",
    "Walnut Grove High School",
    "Willard High School",
    "Bailey Educational Center",
    "Community Learning Center",
    "Glendale High School",
    "Graff Career Center",
    "Hillcrest High School",
    "Kickapoo High School",
    "Parkview High School",
    "Phelps Gifted Center",
    "Springfield Central High School",
    "Christian Schools of Springfield",
    "Grace Classical Academy",
    "Greenwood Laboratory School",
    "New Covenant Academy",
    "Springfield Catholic High School",
    "Summit Preparatory School of Southwest Missouri",
    "Grundy County High School",
    "Trenton High School",
    "Cainsville High School",
    "Gilman City High School",
    "North Harrison County High School",
    "Ridgeway High School",
    "South Harrison County High School",
    "Calhoun High School",
    "Clinton High School",
    "Windsor High School",
    "Montrose High School",
    "Hermitage High School",
    "Skyline High School",
    "Weaubleau High School",
    "Wheatland High School",
    "Craig High School",
    "Mound City High School",
    "South Holt County High School",
    "Fayette High School",
    "Glasgow High School",
    "New Franklin High School",
    "Willow Springs High School",
    "Liberty High School",
    "South Central Career Center",
    "Trinity Christian Academy",
    "Faith Assembly Christian School",
    "West Plains High School",
    "Arcadia Valley High School",
    "Viburnum High School",
    "South Iron County High School",
    "Grain Valley High School",
    "Lone Jack High School",
    "Oak Grove High School",
    "Blue Springs High School",
    "Blue Springs South High School",
    "Valley View High School",
    "Plaza Heights Christian Academy",
    "Grandview Christian School",
    "Grandview High School",
    "Independence",
    "Center Place Restoration School",
    "Fort Osage High School",
    "Independence Academy",
    "McCune School for Boys",
    "Truman High School",
    "Van Horn High School",
    "William Chrisman High School",
    "Center High School",
    "Central High School",
    "East High School",
    "Manual Career & Technical Center",
    "Northeast High School",
    "Ruskin High School",
    "Southeast High School",
    "Charter/magnet schools",
    "Alta Vista Charter School",
    "Hogan Preparatory Academy",
    "Lee A. Tolbert Community Academy",
    "Lincoln College Preparatory Academy",
    "Paseo Academy of Performing Arts",
    "University Academy",
    "Archbishop O'Hara High School",
    "The Barstow School",
    "Blue Ridge Christian School",
    "Cristo Rey Kansas City High School",
    "De la Salle Education Center",
    "Gillis Center School",
    "Heart of America Christian Academy",
    "Kansas City Academy",
    "Lutheran High School of Kansas City",
    "Notre Dame de Sion School",
    "The Pembroke Hill School",
    "Rockhurst High School",
    "St. Paul's Episcopal Day School",
    "St. Teresa's Academy",
    "Seton Center High School",
    "Universal Academy Islamic School",
    "Whitefield Academy",
    "Lee's Summit High School",
    "Lee's Summit North High School",
    "Lee's Summit West High School",
    "St. Michael the Archangel Catholic High School",
    "Summit Christian Academy",
    "Raytown High School",
    "Raytown South High School",
    "Carl Junction High School",
    "Carthage Senior High School",
    "Jasper High School",
    "Sarcoxie High School",
    "Webb City High School",
    "College Heights Christian School",
    "Joplin High School",
    "McAuley Catholic High School",
    "Thomas Jefferson Independent Day School",
    "Crystal City High School",
    "Herculaneum High School",
    "Grandview High School",
    "Northwest High School",
    "Fox High School",
    "People's Christian Academy",
    "De Soto High School",
    "Manna Christian Academy",
    "Festus High School",
    "Jefferson County High School",
    "St. Pius X High School",
    "Twin City Christian Academy",
    "Christian Outreach School",
    "Hillsboro High School",
    "Seckman High School",
    "Windsor High School",
    "Chilhowee High School",
    "Holden High School",
    "Crest Ridge High School",
    "Kingsville High School",
    "Knob Noster High School",
    "Leeton High School",
    "Warrensburg High School",
    "Knox County High School",
    "Conway High School",
    "Lebanon High School",
    "Lafayette County High School",
    "Lexington High School",
    "Odessa High School",
    "Santa Fe High School",
    "Wellington-Napoleon High School",
    "Concordia High School",
    "St. Paul Lutheran High School",
    "Marionville High School",
    "Miller High School",
    "Mount Vernon High School",
    "Pierce City High School",
    "Verona High School",
    "Aurora Christian Academy",
    "Aurora High School",
    "Harvest Christian Academy",
    "Highland High School",
    "Canton High School",
    "Cedar Falls School",
    "Elsberry High School",
    "Silex High School",
    "Troy Holiness School",
    "Troy Buchanan High School/Freshman Center",
    "Calvary Christian School",
    "Winfield High School",
    "Brookfield High School",
    "Bucklin High School",
    "Linn County High School",
    "Marceline High School",
    "Meadville High School",
    "Chillicothe High School",
    "Southwest Livingston County High School",
    "Atlanta High School",
    "Bevier High School",
    "La Plata High School",
    "Macon High School",
    "Macon County High School",
    "Marquand-Zion High School",
    "Faith Christian Academy",
    "Fredericktown High School",
    "Vienna High School",
    "Belle High School",
    "Hannibal High School",
    "Marion County High School",
    "Palmyra High School",
    "McDonald County High School",
    "Mercer High School",
    "Princeton High School",
    "Eldon High School",
    "Tuscumbia High School",
    "St. Elizabeth High School",
    "Osage High School",
    "Iberia High School",
    "Powerhouse Christian Academy",
    "Charleston High School",
    "East Prairie High School",
    "Jamestown High School",
    "California High School",
    "Tipton High School",
    "Morgan County R-I High School",
    "Morgan County R-II High School",
    "Madison High School",
    "Monroe City High School",
    "Foundation for Life Christian School",
    "Paris High School",
    "Montgomery County High School",
    "Wellsville-Middletown High School",
    "Gideon High School",
    "New Madrid County Central High School",
    "Portageville High School",
    "Risco High School",
    "Diamond High School",
    "East Newton County High School",
    "Racine Apostolic Christian School",
    "Seneca High School",
    "Neosho Christian Schools",
    "Neosho High School",
    "Ozark Christian Academy",
    "Trinity Learning Center",
    "Jefferson High School",
    "Nodaway-Holt High School",
    "North Nodaway High School",
    "Northeast Nodaway High School",
    "South Nodaway High School",
    "West Nodaway High School",
    "Maryville High School",
    "Missouri Academy of Science",
    "Alton High School",
    "Couch High School",
    "Koshkonong High School",
    "Thayer High School",
    "Chamois High School",
    "Linn High School",
    "Fatima High School",
    "Bakersfield High School",
    "Dora High School",
    "Gainesville High School",
    "Lutie High School",
    "Caruthersville High School",
    "Cooter High School",
    "Delta High School",
    "Hayti High School",
    "North Pemiscot County High School",
    "South Pemiscot County High School",
    "Perryville High School",
    "St. Vincent de Paul Schools",
    "Green Ridge High School",
    "Northwest High School",
    "Smithton High School",
    "La Monte High School",
    "Show-Me Christian School",
    "Applewood Christian School",
    "Sacred Heart School",
    "Smith-Cotton High School",
    "Newburg High School",
    "Rolla High School",
    "Boys & Girls Town of Missouri School",
    "St. James High School",
    "Bowling Green High School",
    "Clopton High School",
    "Louisiana High School",
    "Pike County Christian School",
    "North Platte County High School",
    "Platte County High School",
    "West Platte County High School",
    "Park Hill High School",
    "Park Hill South High School",
    "Bolivar High School",
    "Fair Play High School",
    "Halfway High School",
    "Humansville High School",
    "Marion C. Early High School",
    "Pleasant Hope High School",
    "Word of God Fellowship Academy",
    "Crocker High School",
    "Dixon High School",
    "Laquey High School",
    "Maranatha Baptist Academy",
    "Richland High School",
    "Waynesville High School",
    "Putnam County High School",
    "Mark Twain High School",
    "Higbee High School",
    "Moberly High School",
    "Northeast Randolph County High School",
    "Westran High School",
    "Hardin-Central High School",
    "Lawson High School",
    "Orrick High School",
    "Richmond High School",
    "Bunker High School",
    "Lesterville High School",
    "Southern Reynolds County High School",
    "Naylor High School",
    "Current River Area Vocational School",
    "Doniphan High School",
    "West Point Christian Academy",
    "Francis Howell Central High School",
    "Francis Howell High School",
    "Liberty High School",
    "Christian High School",
    "Fort Zumwalt Hope High School",
    "Fort Zumwalt North High School",
    "Fort Zumwalt West High School",
    "Liberty Classical School",
    "Living Word Christian Schools",
    "St. Dominic High School",
    "Duchesne High School",
    "Francis Howell Union High School",
    "Lewis & Clark Career Center",
    "Orchard Farm High School",
    "St. Charles High School",
    "St. Charles West High School",
    "Fort Zumwalt East High School",
    "Fort Zumwalt South High School",
    "Francis Howell North High School",
    "Emil E. Holt High School",
    "Timberland High School",
    "Appleton City High School",
    "Osceola High School",
    "Bismarck High School",
    "North St. Francois County High School",
    "Farmington High School",
    "St. Paul Lutheran School",
    "Park Hills",
    "Park Hills Central High School",
    "West St. Francois County High School",
    "Beaumont Technical Center",
    "Carnahan High School of the Future",
    "Central Visual and Performing Arts High School",
    "Clyde C. Miller Career Academy",
    "Collegiate School of Medicine and Bioscience",
    "Fresh Start Academy at Sumner",
    "Gateway STEM High School",
    "Griscom Alternative School",
    "Innovative Concept Academy at Blewett",
    "McKinley Classical Leadership Academy",
    "Metro Academic and Classical High School",
    "Nottingham Community Access and Job Training School",
    "Roosevelt High School",
    "Soldan International Studies High School",
    "Sumner High School",
    "Vashon High School",
    "Bishop DuBourg High School",
    "Cardinal Ritter College Prep High School",
    "Crossroads College Preparatory School",
    "Rosati-Kain High School",
    "St. Louis University High School",
    "St. Mary's High School",
    "Brentwood High School",
    "Clayton High School",
    "Eureka High School",
    "Hazelwood West High School",
    "Incarnate Word Academy",
    "Jennings High School",
    "Lafayette High School",
    "Maplewood Richmond Heights High School",
    "McCluer South-Berkeley High School",
    "Mehlville High School",
    "Oakville High School",
    "Parkway South High School",
    "Pattonville High School",
    "Ritenour High School",
    "Riverview Gardens High School",
    "St. Joseph's Academy",
    "University City High School",
    "Ursuline Academy",
    "Valley Park High School",
    "Affton High School",
    "Cor Jesu Academy",
    "Lutheran High School South",
    "Al Manara Academy",
    "Parkway West High School",
    "Chesterfield",
    "Marquette High School",
    "Parkway Central High School",
    "Fern Ridge High School",
    "Parkway North High School",
    "Chaminade College Preparatory School",
    "De Smet Jesuit High School",
    "St. Louis Priory School",
    "Whitfield School",
    "Visitation Academy of St. Louis",
    "Heritage Classical Christian Academy",
    "Rockwood Summit High School",
    "Hazelwood Central High School",
    "McCluer High School",
    "McCluer North High School",
    "North County Christian School",
    "North Technical High School",
    "Kirkwood High School",
    "St. John Vianney High School",
    "Ladue Horton Watkins High School",
    "John Burroughs School",
    "Mary Institute and St. Louis Country Day School",
    "Westminster Christian Academy",
    "Lemay",
    "Hancock High School",
    "Notre Dame High School",
    "Normandy",
    "Normandy High School",
    "Lutheran High School North",
    "Hazelwood East High School",
    "Trinity Catholic High School",
    "Lindbergh High School",
    "South Technical High School",
    "Thomas Jefferson School",
    "Christian Brothers College High School",
    "Neuwoehner High School",
    "The Principia School",
    "Christian Brothers College High School",
    "Nerinx Hall High School",
    "Webster Groves High School",
    "Ste. Genevieve High School",
    "Valle Catholic Schools",
    "Malta Bend High School",
    "Slater High School",
    "Sweet Springs High School",
    "Calvary Baptist School",
    "Marshall High School",
    "Schuyler County High School",
    "Scotland County High School",
    "Chaffee High School",
    "Oran High School",
    "Scott City High School",
    "Thomas W. Kelly High School",
    "Scott County Central High School",
    "Sikeston High School",
    "Eminence High School",
    "Winona High School",
    "Heartland Christian Academy",
    "North Shelby High School",
    "South Shelby High School",
    "Shiloh Christian School",
    "Advance High School",
    "Bell City High School",
    "Bernie High School",
    "Bloomfield High School",
    "Dexter High School",
    "Puxico High School",
    "Richland High School",
    "Blue Eye High School",
    "Crane High School",
    "Galena High School",
    "Hurley High School",
    "Gibson Technical Center",
    "New Horizons Alternative School",
    "Reeds Spring High School",
    "Green City High School",
    "Milan High School",
    "Newtown-Harris High School",
    "Bradleyville High School",
    "Branson High School",
    "Forsyth High School",
    "Hollister High School",
    "Trinity Christian Academy",
    "Cabool High School",
    "Houston High School",
    "Licking High School",
    "Plato High School",
    "Summersville High School",
    "Bronaugh High School",
    "Nevada High School",
    "Northeast Vernon County High School",
    "Sheldon High School",
    "Warrenton High School",
    "Wright City High School",
    "Kingston High School",
    "Potosi High School",
    "Valley High School",
    "Greenville High School",
    "New Hope Christian Academy",
    "Clearwater High School",
    "Victory Baptist Academy",
    "Fordland High School",
    "Niangua High School",
    "Seymour High School",
    "Marshfield Christian School",
    "Marshfield High School",
    "Worth County High School",
    "Hartville High School",
    "Mansfield High School",
    "Mountain Grove Christian Academy",
    "Mountain Grove High School",
    "Ozark Mountain Technical Center",
    "Liberty Faith Christian Academy",
    "Norwood High School",
]
