from random import sample

categories = ["medical", "school", "child", "community"]

states = ["MO", "KS", "NE", "IA", "WI"]

persons = {
    "medical": [
        "patient",
        "doctor",
        "physician",
        "nurse practitioner",
        "medical provider",
        "GP",
        "PCP",
    ],
    "school": [
        "student",
        "teacher",
        "administrator",
        "principal",
        "teaching aid",
        "school nurse",
    ],
    "child": [
        "son",
        "daughter",
        "kid",
        "child",
        "nephew",
        "niece",
        "nibling",
        "granddaughter",
        "grandchild",
        "grandson",
    ],
    "community": [
        "neighbor",
        "pastor",
        "teacher",
        "coach",
        "cousin",
        "aunt",
        "uncle",
        "babysitter",
        "dentist",
        "doctor",
        "barber",
        "hairdresser",
        "tutor",
        "music teacher",
        "dance instructor",
        "coworker",
        "boss",
    ],
}

medical_verbs = ["prescribed", "is prescribing", "gave", "is giving"]
medical_things = [
    "hormones",
    "estrogen",
    "estrogen patches",
    "estrodol",
    "testosterone",
    "T",
    "estrogen shots",
    "testosterone shots",
    "testosterone jelly",
]

locations = {
    "medical": ["practice", "hospital", "office", "clinic"],
    "school": ["school", "school system", "school district", "college", "high school"],
}

communication_verbs = ["told", "confessed", "said", "informed", "reported", "mentioned"]

school_classes = [
    "math",
    "science",
    "biology",
    "physics",
    "chemistry",
    "earth science",
    "environmental science",
    "zoology",
    "botany",
    "anatomy",
    "physiology",
    "genetics",
    "ecology",
    "meteorology",
    "oceanography",
    "geology",
    "astronomy",
    "statistics",
    "calculus",
    "algebra",
    "geometry",
    "trigonometry",
    "differential equations",
    "economics",
    "macroeconomics",
    "microeconomics",
    "history",
    "geography",
    "world history",
    "US history",
    "government",
    "political science",
    "psychology",
    "sociology",
    "anthropology",
    "philosophy",
    "English literature",
    "creative writing",
    "French",
    "linguistics",
    "computer science",
    "PE",
]
for school_class in sample(list(school_classes), 5):
    persons["school"].append(f"{school_class} teacher")

sports = [
    "bobsledding",
    "synchronized swimming",
    "dragon boat racing",
    "water polo",
    "mountain biking",
    "snowboarding",
    "archery",
    "wingsuit flying",
    "ice climbing",
    "extreme ironing",
    "yachting",
    "sailing",
    "powerlifting",
    "strongman",
    "dodgeball",
    "spearfishing",
    "wakeboarding",
    "kitesurfing",
    "flyboarding",
    "parkour",
    "rock climbing",
    "obstacle course racing",
    "roller derby",
    "underwater hockey",
    "sled dog racing",
]
sports_descriptors = {
    "male": ["boy's", "boys", "boys'", "men's", "mens", "guys', 'guys's, 'guys'"],
    "female": [
        "girls'",
        "girl's",
        "girls",
        "women's",
        "womens",
        "ladies",
        "ladys",
        "ladies'",
        "ladies's",
    ],
    "generic": ["competitive", "varsity", "junior varsity"],
}
sport_action_verbs = ["play", "compete", "participate"]


words_for_guys = ["boy", "young man", "guy"]
words_for_girls = ["girl", "young lady", "lady", "young woman"]

mood_words = [
    "worried",
    "excited",
    "afraid",
    "angry",
    "concerned",
    "ecstatic",
    "devastated",
    "furious",
    "terrified",
    "elated",
    "enraged",
    "overjoyed",
    "heartbroken",
    "livid",
    "petrified",
    "thrilled",
    "indignant",
    "horrified",
    "exhilarated",
    "despairing",
    "incensed",
]

opinion_words = ["against", "in support of"]

verbs = {
    "action": [
        "skydive",
        "scuba dive",
        "bungee jump",
        "learn to surf",
        "climb a mountain",
        "go zorbing",
        "take a trapeze class",
        "take a survival course",
        "do acroyoga",
        "learn archery",
        "take a fencing class",
        "try parkour",
        "learn circus arts",
        "go horseback riding",
        "learn to juggle",
        "try paddleboarding",
        "do tai chi",
        "take a yoga class",
        "try aerial silks",
        "watch TV shows",
        "play video games",
        "read comics",
        "build a sandcastle",
        "knit a scarf",
        "write love letters",
        "try new foods",
        "explore a city",
        "attend concerts",
        "play board games",
        "watch movies",
        "write poetry",
        "attend a stand-up comedy show",
        "solve puzzles",
        "paint by numbers",
        "listen to music",
        "build with Lego bricks",
        "collect stamps",
        "play with slime",
        "make balloon animals",
        "participate in a flash mob",
        "collect rocks",
        "build the Statue of Liberty with lincoln logs",
    ],
    "communication": [
        "told",
        "confessed to",
        "said",
        "informed",
        "reported to",
        "mentioned to",
        "shared with",
    ],
}